name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем системные зависимости (ускоряем за счет кэширования apt)
      - name: Install system dependencies and compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ffmpeg libopencv-dev clang-15 lld-15

      # 3. Настраиваем проект с помощью CMake
      - name: Configure CMake with Clang-15 and C++20
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          mkdir -p build && cd build
          CC=clang-15 CXX=clang++-15 cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DCMAKE_CXX_STANDARD=20

      # 4. Собираем проект
      - name: Build project
        working-directory: ${{ github.workspace }}/build
        run: make -j$(nproc)

      # 5. Запускаем исполняемый файл (если он успешно собрался)
      - name: Run the application
        if: success() # Этот шаг выполнится, только если предыдущий ('Build') прошел без ошибок
        working-directory: ${{ github.workspace }}/build
        run: ./YourProjectName
